name: build
on:
  schedule:
    - cron:  '30 6 * * *'

jobs:
  make-plots-tweet:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - name: checkout repo content
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: setup R
      uses: r-lib/actions/setup-r@v2

    - name: install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::plotly 
          any::processx
          any::reticulate

    - name: Make plots
      run: Rscript -e 'source("make_plot.R")'

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Plots Created" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: Tweet plots
      run: python tweepy_setup.py

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Plots Tweeted" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
